window.RTS_SEED_DATA = [
  {
    "department": "Chief Electrical Inspector Department",
    "total_received": 23423.0,
    "total_completed": 23095.0,
    "completed_within_rts": 23084.0,
    "total_appeals": 5.0,
    "final_appeals": 5.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 7.0,
    "services_on_aas": 7.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Printing And Stationery Department",
    "total_received": 12554.0,
    "total_completed": 12195.0,
    "completed_within_rts": 11862.0,
    "total_appeals": 335.0,
    "final_appeals": 316.0,
    "feedback_avg_rating": 4.5,
    "feedback_count": 1,
    "total_notified_services": 1.0,
    "services_on_aas": 1.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Haryana Excise & Taxation",
    "total_received": 3591415.0,
    "total_completed": 3589502.0,
    "completed_within_rts": 3578225.0,
    "total_appeals": 23000.0,
    "final_appeals": 18190.0,
    "feedback_avg_rating": 1.875,
    "feedback_count": 4,
    "total_notified_services": 23.0,
    "services_on_aas": 23.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Agriculture Department",
    "total_received": 20699.0,
    "total_completed": 20245.0,
    "completed_within_rts": 19096.0,
    "total_appeals": 224.0,
    "final_appeals": 224.0,
    "feedback_avg_rating": 0.5,
    "feedback_count": 1,
    "total_notified_services": 8.0,
    "services_on_aas": 8.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Town And Country Planning",
    "total_received": 41133.0,
    "total_completed": 39578.0,
    "completed_within_rts": 37155.0,
    "total_appeals": 1567.0,
    "final_appeals": 1320.0,
    "feedback_avg_rating": 2.75,
    "feedback_count": 2,
    "total_notified_services": 15.0,
    "services_on_aas": 15.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Employment Department",
    "total_received": 787282.0,
    "total_completed": 783399.0,
    "completed_within_rts": 754888.0,
    "total_appeals": 7694.0,
    "final_appeals": 7592.0,
    "feedback_avg_rating": 2.936,
    "feedback_count": 211,
    "total_notified_services": 10.0,
    "services_on_aas": 8.0,
    "services_not_on_aas": 2.0
  },
  {
    "department": "Haryana Labour Welfare Board (HLWB)",
    "total_received": 1379601.0,
    "total_completed": 1357657.0,
    "completed_within_rts": 1330098.0,
    "total_appeals": 9006.0,
    "final_appeals": 8923.0,
    "feedback_avg_rating": 2.816,
    "feedback_count": 144,
    "total_notified_services": 27.0,
    "services_on_aas": 21.0,
    "services_not_on_aas": 6.0
  },
  {
    "department": "Rural Development Department, Haryana",
    "total_received": 38603.0,
    "total_completed": 38082.0,
    "completed_within_rts": 32439.0,
    "total_appeals": 5544.0,
    "final_appeals": 5503.0,
    "feedback_avg_rating": 3.2812,
    "feedback_count": 112,
    "total_notified_services": 1.0,
    "services_on_aas": 1.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Fisheries Department",
    "total_received": 13831.0,
    "total_completed": 13433.0,
    "completed_within_rts": 12246.0,
    "total_appeals": 540.0,
    "final_appeals": 434.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 52.0,
    "services_on_aas": 41.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Board of School Education Haryana",
    "total_received": 128797.0,
    "total_completed": 128016.0,
    "completed_within_rts": 125425.0,
    "total_appeals": 179.0,
    "final_appeals": 175.0,
    "feedback_avg_rating": 2.625,
    "feedback_count": 4,
    "total_notified_services": 4.0,
    "services_on_aas": 3.0,
    "services_not_on_aas": 1.0
  },
  {
    "department": "Dakshin Haryana Bijli Vitran Nigam-DHBVN",
    "total_received": 6778889.0,
    "total_completed": 6745960.0,
    "completed_within_rts": 6113658.0,
    "total_appeals": 262574.0,
    "final_appeals": 243564.0,
    "feedback_avg_rating": 2.6073,
    "feedback_count": 3154,
    "total_notified_services": 21.0,
    "services_on_aas": 38.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Transport Department",
    "total_received": 26352382.0,
    "total_completed": 26338303.0,
    "completed_within_rts": 23604112.0,
    "total_appeals": 63896.0,
    "final_appeals": 54077.0,
    "feedback_avg_rating": 3.3475,
    "feedback_count": 295,
    "total_notified_services": 37.0,
    "services_on_aas": 32.0,
    "services_not_on_aas": 5.0
  },
  {
    "department": "Social Justice And Empowerment",
    "total_received": 770116.0,
    "total_completed": 765366.0,
    "completed_within_rts": 680392.0,
    "total_appeals": 40806.0,
    "final_appeals": 39468.0,
    "feedback_avg_rating": 2.4815,
    "feedback_count": 460,
    "total_notified_services": 11.0,
    "services_on_aas": 11.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Welfare of SCs And BCs",
    "total_received": 642763.0,
    "total_completed": 639523.0,
    "completed_within_rts": 557987.0,
    "total_appeals": 264054.0,
    "final_appeals": 257037.0,
    "feedback_avg_rating": 2.7174,
    "feedback_count": 1688,
    "total_notified_services": 5.0,
    "services_on_aas": 5.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Haryana Forest Department",
    "total_received": 27631.0,
    "total_completed": 27409.0,
    "completed_within_rts": 25065.0,
    "total_appeals": 552.0,
    "final_appeals": 433.0,
    "feedback_avg_rating": 1.75,
    "feedback_count": 8,
    "total_notified_services": 2.0,
    "services_on_aas": 2.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Public Health And Engineering-PHED",
    "total_received": 2412799.0,
    "total_completed": 2408166.0,
    "completed_within_rts": 2304521.0,
    "total_appeals": 101255.0,
    "final_appeals": 91172.0,
    "feedback_avg_rating": 1.9496,
    "feedback_count": 2122,
    "total_notified_services": 4.0,
    "services_on_aas": 8.0,
    "services_not_on_aas": 1.0
  },
  {
    "department": "Haryana State Ind and Infrastructure Development Co Ltd(HSIIDC)",
    "total_received": 67108.0,
    "total_completed": 66415.0,
    "completed_within_rts": 59393.0,
    "total_appeals": 4833.0,
    "final_appeals": 4257.0,
    "feedback_avg_rating": 2.7308,
    "feedback_count": 13,
    "total_notified_services": 26.0,
    "services_on_aas": 22.0,
    "services_not_on_aas": 5.0
  },
  {
    "department": "Horticulture Department",
    "total_received": 92379.0,
    "total_completed": 92377.0,
    "completed_within_rts": 89960.0,
    "total_appeals": 1183.0,
    "final_appeals": 1070.0,
    "feedback_avg_rating": 4.3333,
    "feedback_count": 3,
    "total_notified_services": 7.0,
    "services_on_aas": 3.0,
    "services_not_on_aas": 4.0
  },
  {
    "department": "Housing Board",
    "total_received": 63643.0,
    "total_completed": 62406.0,
    "completed_within_rts": 48318.0,
    "total_appeals": 11682.0,
    "final_appeals": 8993.0,
    "feedback_avg_rating": 3.2576,
    "feedback_count": 66,
    "total_notified_services": 9.0,
    "services_on_aas": 10.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Labour Department",
    "total_received": 507925.0,
    "total_completed": 507503.0,
    "completed_within_rts": 453267.0,
    "total_appeals": 8925.0,
    "final_appeals": 5387.0,
    "feedback_avg_rating": 1.6176,
    "feedback_count": 17,
    "total_notified_services": 10.0,
    "services_on_aas": 10.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Uttar Haryana Bijli Vitran Nigam-UHBVN",
    "total_received": 6603256.0,
    "total_completed": 6594111.0,
    "completed_within_rts": 6261185.0,
    "total_appeals": 177695.0,
    "final_appeals": 169782.0,
    "feedback_avg_rating": 2.7158,
    "feedback_count": 2340,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Industries and Commerce Department",
    "total_received": 111380.0,
    "total_completed": 110237.0,
    "completed_within_rts": 83000.0,
    "total_appeals": 28008.0,
    "final_appeals": 27413.0,
    "feedback_avg_rating": 2.7318,
    "feedback_count": 110,
    "total_notified_services": 43.0,
    "services_on_aas": 43.0,
    "services_not_on_aas": 1.0
  },
  {
    "department": "Kurukshetra University, Kurukshetra",
    "total_received": 7087.0,
    "total_completed": 6991.0,
    "completed_within_rts": 6690.0,
    "total_appeals": 369.0,
    "final_appeals": 358.0,
    "feedback_avg_rating": 2.95,
    "feedback_count": 10,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Cooperation Department",
    "total_received": 6660.0,
    "total_completed": 6583.0,
    "completed_within_rts": 4457.0,
    "total_appeals": 2868.0,
    "final_appeals": 2764.0,
    "feedback_avg_rating": 4.1562,
    "feedback_count": 16,
    "total_notified_services": 1.0,
    "services_on_aas": 1.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Haryana Backward Classes and Economically Weaker Sections Kalyan Nigam",
    "total_received": 24966.0,
    "total_completed": 24951.0,
    "completed_within_rts": 21936.0,
    "total_appeals": 0.0,
    "final_appeals": 0.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Urban Local Bodies",
    "total_received": 1764155.0,
    "total_completed": 1740021.0,
    "completed_within_rts": 1600528.0,
    "total_appeals": 115184.0,
    "final_appeals": 84743.0,
    "feedback_avg_rating": 2.4083,
    "feedback_count": 1593,
    "total_notified_services": 34.0,
    "services_on_aas": 26.0,
    "services_not_on_aas": 12.0
  },
  {
    "department": "Police Department",
    "total_received": 8575853.0,
    "total_completed": 8559238.0,
    "completed_within_rts": 8151033.0,
    "total_appeals": 52148.0,
    "final_appeals": 51961.0,
    "feedback_avg_rating": 2.1159,
    "feedback_count": 634,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Haryana State Agricultural Marketing Board(HSAMB)",
    "total_received": 15953.0,
    "total_completed": 15720.0,
    "completed_within_rts": 11426.0,
    "total_appeals": 1697.0,
    "final_appeals": 1300.0,
    "feedback_avg_rating": 2.9286,
    "feedback_count": 14,
    "total_notified_services": 8.0,
    "services_on_aas": 9.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Department of Mines & Geology",
    "total_received": 86080.0,
    "total_completed": 84805.0,
    "completed_within_rts": 84767.0,
    "total_appeals": 512.0,
    "final_appeals": 193.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Directorate of Fire and Emergency Service Haryana",
    "total_received": 155589.0,
    "total_completed": 154259.0,
    "completed_within_rts": 146162.0,
    "total_appeals": 3267.0,
    "final_appeals": 1691.0,
    "feedback_avg_rating": 3.2,
    "feedback_count": 5,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Women and Child Development Department",
    "total_received": 571908.0,
    "total_completed": 549499.0,
    "completed_within_rts": 391640.0,
    "total_appeals": 49879.0,
    "final_appeals": 33606.0,
    "feedback_avg_rating": 3.135,
    "feedback_count": 237,
    "total_notified_services": 10.0,
    "services_on_aas": 10.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Building and Other Construction Workers (BOCW) Board",
    "total_received": 5284458.0,
    "total_completed": 5284201.0,
    "completed_within_rts": 4351892.0,
    "total_appeals": 42615.0,
    "final_appeals": 42293.0,
    "feedback_avg_rating": 3.1535,
    "feedback_count": 228,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Food Civil Supplies & Consumer Affairs Department",
    "total_received": 2430.0,
    "total_completed": 2374.0,
    "completed_within_rts": 2258.0,
    "total_appeals": 614.0,
    "final_appeals": 527.0,
    "feedback_avg_rating": 4.75,
    "feedback_count": 2,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Revenue & Disaster Management Department",
    "total_received": 27697148.0,
    "total_completed": 27639979.0,
    "completed_within_rts": 26434620.0,
    "total_appeals": 778457.0,
    "final_appeals": 710694.0,
    "feedback_avg_rating": 2.7418,
    "feedback_count": 3867,
    "total_notified_services": 50.0,
    "services_on_aas": 15.0,
    "services_not_on_aas": 39.0
  },
  {
    "department": "Public Works Department (Buildings and Roads)",
    "total_received": 4021.0,
    "total_completed": 3839.0,
    "completed_within_rts": 2894.0,
    "total_appeals": 514.0,
    "final_appeals": 413.0,
    "feedback_avg_rating": 4.5,
    "feedback_count": 3,
    "total_notified_services": 5.0,
    "services_on_aas": 4.0,
    "services_not_on_aas": 1.0
  },
  {
    "department": "Health Services Department",
    "total_received": 6413626.0,
    "total_completed": 6372037.0,
    "completed_within_rts": 6012031.0,
    "total_appeals": 197648.0,
    "final_appeals": 190200.0,
    "feedback_avg_rating": 2.9329,
    "feedback_count": 2770,
    "total_notified_services": 19.0,
    "services_on_aas": 5.0,
    "services_not_on_aas": 18.0
  },
  {
    "department": "Haryana State Seed Certification Agency",
    "total_received": 510.0,
    "total_completed": 489.0,
    "completed_within_rts": 404.0,
    "total_appeals": 102.0,
    "final_appeals": 99.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 3.0,
    "services_on_aas": 3.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Haryana Shehari Vikas Pradhikaran",
    "total_received": 867269.0,
    "total_completed": 863650.0,
    "completed_within_rts": 597778.0,
    "total_appeals": 245315.0,
    "final_appeals": 188535.0,
    "feedback_avg_rating": 3.1032,
    "feedback_count": 712,
    "total_notified_services": 52.0,
    "services_on_aas": 69.0,
    "services_not_on_aas": 14.0
  },
  {
    "department": "Haryana State Pollution Control Board",
    "total_received": 55841.0,
    "total_completed": 55293.0,
    "completed_within_rts": 54319.0,
    "total_appeals": 0.0,
    "final_appeals": 0.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 8.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 8.0
  },
  {
    "department": "Sainik And Ardh Sainik Welfare Department",
    "total_received": 991.0,
    "total_completed": 920.0,
    "completed_within_rts": 651.0,
    "total_appeals": 44.0,
    "final_appeals": 32.0,
    "feedback_avg_rating": 4.5,
    "feedback_count": 1,
    "total_notified_services": 18.0,
    "services_on_aas": 18.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Dada Lakhmi Chand State University of Performing and Visual Arts",
    "total_received": 36.0,
    "total_completed": 36.0,
    "completed_within_rts": 36.0,
    "total_appeals": 2.0,
    "final_appeals": 2.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Directorate of Information, Public Relations & Languages",
    "total_received": 165.0,
    "total_completed": 133.0,
    "completed_within_rts": 133.0,
    "total_appeals": 61.0,
    "final_appeals": 40.0,
    "feedback_avg_rating": 4.5,
    "feedback_count": 2,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Maharishi Dayanand University, Rohtak",
    "total_received": 362.0,
    "total_completed": 308.0,
    "completed_within_rts": 269.0,
    "total_appeals": 79.0,
    "final_appeals": 75.0,
    "feedback_avg_rating": 3.5,
    "feedback_count": 2,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Maharshi Valmiki Sanskrit University, Kaithal",
    "total_received": 24.0,
    "total_completed": 23.0,
    "completed_within_rts": 23.0,
    "total_appeals": 0.0,
    "final_appeals": 0.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Guru Jambheshwar University of Science And Technology, Hisar",
    "total_received": 265.0,
    "total_completed": 189.0,
    "completed_within_rts": 176.0,
    "total_appeals": 57.0,
    "final_appeals": 55.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Dr Bhim Rao Ambedkar Law University, Sonepat",
    "total_received": 4.0,
    "total_completed": 4.0,
    "completed_within_rts": 4.0,
    "total_appeals": 0.0,
    "final_appeals": 0.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Bhagat Phool Singh Mahila Mahavidyalaya, Khanpur Kalan (Sonepat)",
    "total_received": 16.0,
    "total_completed": 10.0,
    "completed_within_rts": 10.0,
    "total_appeals": 1.0,
    "final_appeals": 1.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "J.C. Bose University of Science and Technology YMCA Faridabad",
    "total_received": 1.0,
    "total_completed": 1.0,
    "completed_within_rts": 1.0,
    "total_appeals": 0.0,
    "final_appeals": 0.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "The NorthCap University",
    "total_received": 1.0,
    "total_completed": 1.0,
    "completed_within_rts": 1.0,
    "total_appeals": 0.0,
    "final_appeals": 0.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Indira Gandhi University, Meerpur (Rewari)",
    "total_received": 8.0,
    "total_completed": 1.0,
    "completed_within_rts": 1.0,
    "total_appeals": 0.0,
    "final_appeals": 0.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Science and Technology Department",
    "total_received": 3789.0,
    "total_completed": 3789.0,
    "completed_within_rts": 1900.0,
    "total_appeals": 18.0,
    "final_appeals": 16.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 2.0,
    "services_on_aas": 2.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Chaudhary Devi Lal University, Sirsa",
    "total_received": 23.0,
    "total_completed": 22.0,
    "completed_within_rts": 11.0,
    "total_appeals": 19.0,
    "final_appeals": 12.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Gurugram Metropolitan Development Authority",
    "total_received": 618.0,
    "total_completed": 537.0,
    "completed_within_rts": 284.0,
    "total_appeals": 134.0,
    "final_appeals": 108.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 15.0,
    "services_on_aas": 15.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Faridabad Metropolitan Development Authority",
    "total_received": 179.0,
    "total_completed": 153.0,
    "completed_within_rts": 59.0,
    "total_appeals": 93.0,
    "final_appeals": 85.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 15.0,
    "services_on_aas": 15.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Deenbandhu Chhotu Ram University Of Science & Technology Murthal Sonipat",
    "total_received": 12.0,
    "total_completed": 0.0,
    "completed_within_rts": 0.0,
    "total_appeals": 11.0,
    "final_appeals": 11.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Haryana State Board of Technical Education",
    "total_received": 1334.0,
    "total_completed": 1334.0,
    "completed_within_rts": 475.0,
    "total_appeals": 14.0,
    "final_appeals": 14.0,
    "feedback_avg_rating": 3.0,
    "feedback_count": 1,
    "total_notified_services": 8.0,
    "services_on_aas": 8.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Chaudhary Bansi Lal University, Bhiwani",
    "total_received": 42.0,
    "total_completed": 0.0,
    "completed_within_rts": 0.0,
    "total_appeals": 12.0,
    "final_appeals": 12.0,
    "feedback_avg_rating": 5.0,
    "feedback_count": 1,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Sonipat Metropolitan Development Authority",
    "total_received": 185.0,
    "total_completed": 43.0,
    "completed_within_rts": 29.0,
    "total_appeals": 16.0,
    "final_appeals": 0.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 5.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Citizen Resource Information Department",
    "total_received": 37429.0,
    "total_completed": 33943.0,
    "completed_within_rts": 21065.0,
    "total_appeals": 0.0,
    "final_appeals": 0.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Haryana Women Development Corporation",
    "total_received": 3471.0,
    "total_completed": 3446.0,
    "completed_within_rts": 777.0,
    "total_appeals": 38.0,
    "final_appeals": 38.0,
    "feedback_avg_rating": 0.5,
    "feedback_count": 1,
    "total_notified_services": 3.0,
    "services_on_aas": 3.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Secondary Education Department Haryana",
    "total_received": 679.0,
    "total_completed": 221.0,
    "completed_within_rts": 138.0,
    "total_appeals": 22.0,
    "final_appeals": 0.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 3.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 3.0
  },
  {
    "department": "Development and Panchayats Department",
    "total_received": 1148.0,
    "total_completed": 997.0,
    "completed_within_rts": 210.0,
    "total_appeals": 3323.0,
    "final_appeals": 1686.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 1.0,
    "services_on_aas": 1.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Chaudhary Ranbir Singh University, Jind",
    "total_received": 2962.0,
    "total_completed": 531.0,
    "completed_within_rts": 446.0,
    "total_appeals": 2298.0,
    "final_appeals": 2289.0,
    "feedback_avg_rating": 4.1111,
    "feedback_count": 9,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Directorate of MSME",
    "total_received": 8287.0,
    "total_completed": 6577.0,
    "completed_within_rts": 2576.0,
    "total_appeals": 6660.0,
    "final_appeals": 4538.0,
    "feedback_avg_rating": 3.6364,
    "feedback_count": 11,
    "total_notified_services": 17.0,
    "services_on_aas": 48.0,
    "services_not_on_aas": 3.0
  },
  {
    "department": "Gurugram University, Gurugram",
    "total_received": 423.0,
    "total_completed": 0.0,
    "completed_within_rts": 0.0,
    "total_appeals": 398.0,
    "final_appeals": 328.0,
    "feedback_avg_rating": 1.5714,
    "feedback_count": 7,
    "total_notified_services": 0.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 0.0
  },
  {
    "department": "Animal Husbandry and Dairying",
    "total_received": 746737.0,
    "total_completed": 719153.0,
    "completed_within_rts": 207832.0,
    "total_appeals": 135640.0,
    "final_appeals": 132415.0,
    "feedback_avg_rating": 2.5186,
    "feedback_count": 915,
    "total_notified_services": 6.0,
    "services_on_aas": 4.0,
    "services_not_on_aas": 2.0
  },
  {
    "department": "Home Department",
    "total_received": 104959.0,
    "total_completed": 71107.0,
    "completed_within_rts": 21927.0,
    "total_appeals": 0.0,
    "final_appeals": 0.0,
    "feedback_avg_rating": 0,
    "feedback_count": 0,
    "total_notified_services": 48.0,
    "services_on_aas": 19.0,
    "services_not_on_aas": 30.0
  },
  {
    "department": "Haryana Scheduled Castes Finance and Development Corporation",
    "total_received": 6458.0,
    "total_completed": 3968.0,
    "completed_within_rts": 101.0,
    "total_appeals": 75.0,
    "final_appeals": 75.0,
    "feedback_avg_rating": 4.5,
    "feedback_count": 1,
    "total_notified_services": 9.0,
    "services_on_aas": 0.0,
    "services_not_on_aas": 9.0
  }
];
